# Generated by Django 6.0.2 on 2026-02-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(help_text='Zkratka jezdce (VER, HAM...)', max_length=3)),
                ('full_name', models.CharField(help_text='Celé jméno', max_length=100)),
                ('number', models.IntegerField(help_text='Číslo jezdce')),
                ('team', models.CharField(help_text='Název týmu', max_length=100)),
                ('team_color', models.CharField(default='#ffffff', help_text='Barva týmu (#hex)', max_length=7)),
                ('grid_position', models.IntegerField(default=0, help_text='Startovní pozice')),
                ('status', models.CharField(default='Running', help_text='Stav (Running, DNF, +1 Lap...)', max_length=50)),
                ('is_fastest_lap', models.BooleanField(default=False, help_text='Má nejrychlejší kolo?')),
            ],
            options={
                'ordering': ['grid_position'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Rok sezóny')),
                ('round_number', models.IntegerField(help_text='Číslo závodu v sezóně')),
                ('grand_prix', models.CharField(help_text='Název Grand Prix', max_length=100)),
                ('country', models.CharField(help_text='Stát', max_length=100)),
                ('circuit_name', models.CharField(help_text='Název okruhu', max_length=200)),
                ('circuit_length_km', models.FloatField(default=0, help_text='Délka okruhu v km')),
                ('total_laps', models.IntegerField(default=0, help_text='Celkový počet kol')),
                ('current_lap', models.IntegerField(default=0, help_text='Aktuální simulované kolo')),
                ('is_running', models.BooleanField(default=False, help_text='Je simulace aktivní?')),
                ('is_finished', models.BooleanField(default=False, help_text='Je závod dokončen?')),
                ('weather', models.CharField(default='—', help_text='Počasí', max_length=50)),
                ('air_temp', models.FloatField(blank=True, help_text='Teplota vzduchu °C', null=True)),
                ('track_temp', models.FloatField(blank=True, help_text='Teplota trati °C', null=True)),
                ('safety_car', models.CharField(choices=[('NONE', 'Žádný'), ('SC', 'Safety Car'), ('VSC', 'Virtual Safety Car'), ('RED', 'Červená vlajka')], default='NONE', help_text='Stav Safety Caru v aktuálním kole', max_length=20)),
                ('data_loaded', models.BooleanField(default=False, help_text='Byla data načtena z FastF1?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-round_number'],
                'unique_together': {('year', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Kolo incidentu')),
                ('incident_type', models.CharField(choices=[('SC', 'Safety Car'), ('VSC', 'Virtual Safety Car'), ('RED', 'Červená vlajka'), ('PENALTY', 'Penalizace'), ('DNF', 'Odstoupení'), ('OTHER', 'Jiné')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Popis incidentu')),
                ('driver', models.ForeignKey(blank=True, help_text='Dotčený jezdec (volitelné)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='live.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='live.race')),
            ],
            options={
                'ordering': ['lap_number'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='live.race'),
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Kolo pitstop')),
                ('stop_number', models.IntegerField(default=1, help_text='Kolikátý pitstop')),
                ('duration_ms', models.FloatField(blank=True, help_text='Doba pitstop v ms', null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitstops', to='live.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitstops', to='live.race')),
            ],
            options={
                'ordering': ['lap_number'],
                'unique_together': {('race', 'driver', 'stop_number')},
            },
        ),
        migrations.CreateModel(
            name='LapTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Číslo kola')),
                ('position', models.IntegerField(help_text='Pozice v tomto kole')),
                ('lap_time_ms', models.FloatField(blank=True, help_text='Čas kola v milisekundách', null=True)),
                ('sector1_ms', models.FloatField(blank=True, help_text='Sektor 1 v ms', null=True)),
                ('sector2_ms', models.FloatField(blank=True, help_text='Sektor 2 v ms', null=True)),
                ('sector3_ms', models.FloatField(blank=True, help_text='Sektor 3 v ms', null=True)),
                ('delta_to_leader_ms', models.FloatField(blank=True, help_text='Ztráta na lídra v ms', null=True)),
                ('is_personal_best', models.BooleanField(default=False, help_text='Osobní nejlepší kolo?')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_timings', to='live.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_timings', to='live.race')),
            ],
            options={
                'ordering': ['lap_number', 'position'],
                'unique_together': {('race', 'driver', 'lap_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('race', 'abbreviation')},
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(help_text='Číslo kola')),
                ('distance', models.TextField(help_text='JSON pole vzdáleností (m)')),
                ('speed', models.TextField(help_text='JSON pole rychlostí (km/h)')),
                ('throttle', models.TextField(help_text='JSON pole polohy plynu (0–100)')),
                ('brake', models.TextField(help_text='JSON pole brzdění (0/1 nebo 0–100)')),
                ('gear', models.TextField(default='[]', help_text='JSON pole převodového stupně')),
                ('drs', models.TextField(default='[]', help_text='JSON pole DRS (0/1)')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='live.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='live.race')),
            ],
            options={
                'ordering': ['driver', 'lap_number'],
                'unique_together': {('race', 'driver', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='TyreStint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stint_number', models.IntegerField(default=1, help_text='Kolikátý stint')),
                ('compound', models.CharField(choices=[('SOFT', 'Soft'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('INTERMEDIATE', 'Intermediate'), ('WET', 'Wet'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('start_lap', models.IntegerField(help_text='Počáteční kolo stintu')),
                ('end_lap', models.IntegerField(blank=True, help_text='Koncové kolo stintu', null=True)),
                ('tyre_age', models.IntegerField(default=0, help_text='Stáří pneumatiky (kola)')),
                ('is_new', models.BooleanField(default=True, help_text='Nová sada?')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_stints', to='live.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_stints', to='live.race')),
            ],
            options={
                'ordering': ['driver', 'stint_number'],
                'unique_together': {('race', 'driver', 'stint_number')},
            },
        ),
    ]
